# This file is auto-synced from product-os/jellyfish-config/.resinci.yml
# and should only be edited there!

npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "16"

docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: sut
      publish: false
      args:
        - BUILDKIT_INLINE_CACHE=1
